Repository SU-SWS/ace-stanfordlagunita, pull requests merged in 2023-03, with the labels that each got.

#28 SUL23-135 | @jdwjdwjdw | Remove drop cap, splash text, and callout text from wysiwyg
  docroot/profiles/custom/sul_profile/config/sync/editor.editor.stanford_html.yml
Labels: size/xs

#25 SUL23-118 | @jdwjdwjdw | Add address and map link to contact card paragraph
  docroot/profiles/custom/sul_profile/config/sync/core.entity_form_display.paragraph.sul_contact_card.default.yml
  docroot/profiles/custom/sul_profile/config/sync/core.entity_view_display.paragraph.sul_contact_card.default.yml
  docroot/profiles/custom/sul_profile/config/sync/field.field.paragraph.sul_contact_card.sul_contact__address.yml
  docroot/profiles/custom/sul_profile/config/sync/field.field.paragraph.sul_contact_card.sul_contact__map_link.yml
  docroot/profiles/custom/sul_profile/config/sync/field.storage.paragraph.sul_contact__address.yml
  docroot/profiles/custom/sul_profile/config/sync/field.storage.paragraph.sul_contact__map_link.yml
  docroot/profiles/custom/sul_profile/config/sync/jsonapi_extras.jsonapi_resource_config.paragraph--sul_contact_card.yml
Labels: size/s

#30 SUL23-157 Disable event series for non-admins
  docroot/profiles/custom/sul_profile/config/sync/user.role.contributor.yml
  docroot/profiles/custom/sul_profile/config/sync/user.role.site_builder.yml
  docroot/profiles/custom/sul_profile/config/sync/user.role.site_developer.yml
  docroot/profiles/custom/sul_profile/config/sync/user.role.site_editor.yml
  docroot/profiles/custom/sul_profile/config/sync/user.role.site_manager.yml
  docroot/profiles/custom/sul_profile/modules/sul_helper/src/Layouts/SulTwoColumn.php
  docroot/profiles/custom/sul_profile/tests/codeception/acceptance/Content/CoursesCest.php
  docroot/profiles/custom/sul_profile/tests/codeception/acceptance/Content/EventsSeriesCest.php
  docroot/profiles/custom/sul_profile/tests/codeception/acceptance/Content/PolicyCest.php
  docroot/profiles/custom/sul_profile/tests/codeception/acceptance/Content/PublicationsCest.php
Labels: size/l

#31 SUL23118 | @jdwjdwjdw | Update map link and address config
  docroot/profiles/custom/sul_profile/config/sync/core.entity_form_display.paragraph.sul_contact_card.default.yml
  docroot/profiles/custom/sul_profile/modules/sul_helper/src/EventSubscriber/SulFormSubscriber.php
Labels: size/xs

#32 SUL23-120 | @jdwjdwjdw | Add contact image json data for Places to Study node
  docroot/profiles/custom/sul_profile/config/sync/jsonapi_extras.jsonapi_resource_config.node--sul_study_place.yml
Labels: size/xs

#29 Sul23 160 sprinkles option for horizontal cards
  .ddev/config.yaml
  docroot/profiles/custom/sul_profile/modules/sul_helper/src/Plugin/paragraphs/Behavior/CardBehaviors.php
Labels: patch, size/xs

#33 Adjusted tests for hidden Superhead field
  composer.lock
  docroot/profiles/custom/sul_profile/tests/codeception/acceptance/Paragraphs/ListsCest.php
  docroot/profiles/custom/sul_profile/tests/codeception/functional/Content/BasicPageParagraphsCest.php
  docroot/sites/settings/ci.settings.php
Labels: size/xs

#34 SUL23-137 Added "Simple Button" paragraph type
  composer.lock
  docroot/profiles/custom/sul_profile/config/sync/core.entity_form_display.paragraph.sul_button.default.yml
  docroot/profiles/custom/sul_profile/config/sync/core.entity_view_display.paragraph.sul_button.default.yml
  docroot/profiles/custom/sul_profile/config/sync/field.field.node.stanford_page.su_page_components.yml
  docroot/profiles/custom/sul_profile/config/sync/field.field.paragraph.sul_button.sul_button_headline.yml
  docroot/profiles/custom/sul_profile/config/sync/field.field.paragraph.sul_button.sul_button_link.yml
  docroot/profiles/custom/sul_profile/config/sync/field.storage.paragraph.sul_button_headline.yml
  docroot/profiles/custom/sul_profile/config/sync/field.storage.paragraph.sul_button_link.yml
  docroot/profiles/custom/sul_profile/config/sync/jsonapi_extras.jsonapi_resource_config.paragraph--sul_button.yml
  docroot/profiles/custom/sul_profile/config/sync/migrate_plus.migration.stanford_localist_importer.yml
  docroot/profiles/custom/sul_profile/config/sync/next.settings.yml
  docroot/profiles/custom/sul_profile/config/sync/paragraphs.paragraphs_type.sul_button.yml
  docroot/profiles/custom/sul_profile/config/sync/user.role.anonymous.yml
  docroot/profiles/custom/sul_profile/modules/sul_helper/src/Plugin/paragraphs/Behavior/SimpleButtonBehaviors.php
Labels: size/s

#37 Updated paragraph form displays
  docroot/profiles/custom/sul_profile/config/sync/core.entity_form_display.paragraph.collection.default.yml
  docroot/profiles/custom/sul_profile/config/sync/core.entity_form_display.paragraph.stanford_banner.default.yml
  docroot/profiles/custom/sul_profile/config/sync/core.entity_form_display.paragraph.sul_button.default.yml
  docroot/profiles/custom/sul_profile/config/sync/core.entity_form_display.paragraph.sul_feat_collection.default.yml
  docroot/profiles/custom/sul_profile/config/sync/field.field.paragraph.collection_card.sul_card_info.yml
  docroot/profiles/custom/sul_profile/config/sync/user.role.contributor.yml
  docroot/profiles/custom/sul_profile/config/sync/user.role.site_builder.yml
  docroot/profiles/custom/sul_profile/config/sync/user.role.site_developer.yml
  docroot/profiles/custom/sul_profile/config/sync/user.role.site_editor.yml
  docroot/profiles/custom/sul_profile/config/sync/user.role.site_manager.yml
  docroot/profiles/custom/sul_profile/sul_profile.profile
  docroot/profiles/custom/sul_profile/tests/codeception/acceptance/Content/EventsCest.php
Labels: size/l

#36 SUL23-154 | @jdwjdwjdw | Update capacity term name
  docroot/profiles/custom/sul_profile/config/sync/core.entity_form_display.node.sul_study_place.default.yml
  docroot/profiles/custom/sul_profile/config/sync/core.entity_view_display.node.sul_study_place.default.yml
  docroot/profiles/custom/sul_profile/config/sync/core.entity_view_display.node.sul_study_place.teaser.yml
  docroot/profiles/custom/sul_profile/config/sync/field.field.node.sul_study_place.sul_study__capacity.yml
  docroot/profiles/custom/sul_profile/config/sync/field.storage.node.sul_study__capacity.yml
Labels: size/l

#38 SUL23-120 | @jdwjdwjdw | Fix study place capacity jsonapi
  docroot/profiles/custom/sul_profile/config/sync/jsonapi_extras.jsonapi_resource_config.node--sul_study_place.yml
Labels: size/xs
