Repository SU-SWS/ace-stanfordlagunita, pull requests merged in 2024-05, with the labels that each got.

#92 SUL-23-447: Added people table view
  docroot/profiles/lagunita/sul_profile/config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_people.yml
Labels: size/m

#94 SUM-113 - Card variant
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/summer_helper.module
Labels: size/xs

#95 Enable accordian
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.field.field.node.stanford_page.su_page_components.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.graphql_compose.settings.yml
Labels: size/xs

#97 SUM-114 - Adding video paragraph type
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.field.field.node.stanford_page.su_page_components.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.graphql_compose.settings.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_form_display.paragraph.sum_video.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_view_display.paragraph.sum_video.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_video.sum_video_video.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_video_video.yml
  docroot/profiles/lagunita/summer_profile/config/summer/paragraphs.paragraphs_type.sum_video.yml
Labels: size/s

#100 SUM-113 - addendum: adding pill background variant
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
Labels: size/xs

#98 SUL23-434: Set up shared tags events view
  docroot/profiles/lagunita/sul_profile/config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_shared_tag_events.yml
Labels: size/m

#102 SUM-113 - background state condition depending on pill selection
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
Labels: size/xs

#104 FIXUP - Missing GraphQL query and codesniff
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.graphql_compose.settings.yml
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerTopBannerBehaviors.php
Labels: size/xs

#106 SUM-109 - Arc Paragraph
  .github/workflows/tests.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.field.field.node.stanford_page.su_page_banner.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.field.field.node.stanford_page.su_page_components.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.graphql_compose.settings.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.search_api.index.algolia_search.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_form_display.paragraph.sum_arc_banner.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_view_display.paragraph.sum_arc_banner.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_arc_banner.sum_arc_description.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_arc_banner.sum_arc_headline.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_arc_banner.sum_arc_image.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_arc_banner.sum_arc_superhead.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_arc_description.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_arc_headline.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_arc_image.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_arc_superhead.yml
  docroot/profiles/lagunita/summer_profile/config/summer/paragraphs.paragraphs_type.sum_arc_banner.yml
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerTopBannerBehaviors.php
Labels: size/s
