Repository SU-SWS/ace-stanfordlagunita, pull requests merged in 2024-06, with the labels that each got.

#110 SUM-110 - adding behavior.
  docroot/profiles/lagunita/sul_profile/tests/codeception/functional/Content/BasicPageParagraphsCest.php
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.field.field.node.stanford_page.su_page_banner.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.paragraphs.paragraphs_type.stanford_banner.yml
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerBannerBehaviors.php
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerTopBannerBehaviors.php
Labels: size/s

#108 SUM-115 - At-a-glance
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.field.field.node.stanford_page.su_page_components.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.graphql_compose.settings.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.search_api.index.algolia_search.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_form_display.paragraph.sum_at_a_glance.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_form_display.paragraph.sum_facts.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_view_display.paragraph.sum_at_a_glance.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_view_display.paragraph.sum_facts.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_at_a_glance.sum_at_a_glance_descrip.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_at_a_glance.sum_at_a_glance_facts.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_at_a_glance.sum_at_a_glance_headline.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_at_a_glance.sum_at_a_glance_link.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_facts.sum_facts_label.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_facts.sum_facts_text.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_at_a_glance_descrip.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_at_a_glance_facts.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_at_a_glance_headline.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_at_a_glance_link.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_facts_label.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_facts_text.yml
  docroot/profiles/lagunita/summer_profile/config/summer/paragraphs.paragraphs_type.sum_at_a_glance.yml
  docroot/profiles/lagunita/summer_profile/config/summer/paragraphs.paragraphs_type.sum_facts.yml
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerAtAGlanceBehaviors.php
Labels: size/m

#111 SUM-111 - Testimonial banner
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.field.field.node.stanford_page.su_page_components.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.graphql_compose.settings.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_form_display.paragraph.sum_testimonial.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_view_display.paragraph.sum_testimonial.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_affi.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_bkg_img.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_button.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_descrip.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_heading.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_hs_video.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_name.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_type.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_univ.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_testimonial_affi.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_testimonial_bkg_img.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_testimonial_button.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_testimonial_descrip.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_testimonial_heading.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_testimonial_hs_video.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_testimonial_name.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_testimonial_type.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_testimonial_univ.yml
  docroot/profiles/lagunita/summer_profile/config/summer/paragraphs.paragraphs_type.sum_at_a_glance.yml
  docroot/profiles/lagunita/summer_profile/config/summer/paragraphs.paragraphs_type.sum_testimonial.yml
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerTestimonialBannerBehaviors.php
Labels: size/m

#117 2.4.5
  CHANGELOG.md
  composer.lock
Labels: patch, size/xs

#120 FIXUP - card number and banner overlay
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.core.entity_form_display.node.stanford_page.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.field.field.node.stanford_page.su_page_components.yml
  docroot/profiles/lagunita/summer_profile/config/summer/core.entity_form_display.paragraph.sum_top_banner.default.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_top_banner.sum_top_banner_cards.yml
  docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_top_banner_cards.yml
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerTopBannerBehaviors.php
Labels: size/xs

#121 SUP: Excerpt ancillary pages content type and permission updates
  composer.json
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Paragraphs/PageTitleBannerCest.php
  docroot/profiles/lagunita/supress/config/supress/config_split.patch.field.field.media.file.field_media_file.yml
  docroot/profiles/lagunita/supress/config/supress/config_split.patch.graphql_compose.settings.yml
  docroot/profiles/lagunita/supress/config/supress/config_split.patch.search_api.index.algolia_search.yml
  docroot/profiles/lagunita/supress/config/supress/config_split.patch.search_api.index.full_site_content.yml
  docroot/profiles/lagunita/supress/config/supress/config_split.patch.user.role.contributor.yml
  docroot/profiles/lagunita/supress/config/supress/config_split.patch.user.role.site_builder.yml
  docroot/profiles/lagunita/supress/config/supress/config_split.patch.user.role.site_developer.yml
  docroot/profiles/lagunita/supress/config/supress/config_split.patch.user.role.site_editor.yml
  docroot/profiles/lagunita/supress/config/supress/config_split.patch.user.role.site_manager.yml
  docroot/profiles/lagunita/supress/config/supress/core.base_field_override.node.sup_book_ancillary.promote.yml
  docroot/profiles/lagunita/supress/config/supress/core.entity_form_display.node.sup_book_ancillary.default.yml
  docroot/profiles/lagunita/supress/config/supress/core.entity_view_display.node.sup_book_ancillary.default.yml
  docroot/profiles/lagunita/supress/config/supress/core.entity_view_display.node.sup_book_ancillary.search_indexing.yml
  docroot/profiles/lagunita/supress/config/supress/core.entity_view_display.node.sup_book_ancillary.teaser.yml
  docroot/profiles/lagunita/supress/config/supress/field.field.node.sup_book_ancillary.sup_ancillary_book.yml
  docroot/profiles/lagunita/supress/config/supress/field.field.node.sup_book_ancillary.sup_ancillary_paragraphs.yml
  docroot/profiles/lagunita/supress/config/supress/field.field.paragraph.sup_file_list.sup_file_list_label.yml
  docroot/profiles/lagunita/supress/config/supress/field.storage.node.sup_ancillary_book.yml
  docroot/profiles/lagunita/supress/config/supress/field.storage.node.sup_ancillary_paragraphs.yml
  docroot/profiles/lagunita/supress/config/supress/node.type.sup_book_ancillary.yml
  docroot/profiles/lagunita/supress/config/supress/pathauto.pattern.sup_book_ancillary.yml
  docroot/profiles/lagunita/supress/config/supress/rabbit_hole.behavior_settings.node_type_sup_book_ancillary.yml
  docroot/profiles/lagunita/supress/config/supress/views.view.sup_books.yml
  docroot/profiles/lagunita/supress/config/sync/config_split.config_split.supress.yml
  docroot/profiles/lagunita/supress/modules/supress_helper/src/Plugin/QueueWorker/BookAncillaryMigrator.php
  docroot/profiles/lagunita/supress/modules/supress_helper/supress_helper.module
  docroot/profiles/lagunita/supress/tests/codeception/acceptance/Content/CustomBlockCest.php
  docroot/profiles/lagunita/supress/tests/codeception/acceptance/Paragraphs/TeaserCest.php
Labels: size/m

#122 SUL23-489: Modified places to study view to allow table option
  docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_study_places.yml
Labels: size/s

#125 SUL23-490: Added branch locations view to support tabular layout
  docroot/profiles/lagunita/sul_profile/config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_branch_locations.yml
Labels: size/m

#124 SUM-186 - Fixup: Moving transparent background to card from pill.
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/summer_helper.install
  docroot/profiles/lagunita/summer_profile/tests/codeception/functional/Navigation/NavigationDropDownsCest.php
  docroot/sites/settings/ci.settings.php
Labels: size/xs

#126 FIXUP - Docs clarification on running groups with blt codeception
  docs/testing.md
Labels: size/xs

#116 SUM-137 - permissions for taxonomy and content type
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.field.field.node.stanford_page.su_page_components.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.user.role.contributor.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.user.role.site_editor.yml
  docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.user.role.site_manager.yml
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/CoursesCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/DefaultContentCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/EventsCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/EventsSeriesCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/NewsCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/PersonCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/PolicyCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/PublicationsCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Paragraphs/ListsCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Paragraphs/TeaserCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Users/IntranetCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/functional/Content/EventsCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/functional/Content/StanfordNewsCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: size/s
