Repository SU-SWS/ace-stanfordlagunita, pull requests merged in 2024-01, with the labels that each got.

#59 Removed duplicated code
  docroot/profiles/custom/sul_profile/config/sync/build_hooks.frontend_environment.sul_public.yml
  docroot/profiles/custom/sul_profile/config/sync/config_ignore.settings.yml
  docroot/profiles/custom/sul_profile/modules/sul_helper/src/Plugin/Next/Revalidator/RedirectPath.php
  docroot/profiles/custom/sul_profile/modules/sul_helper/src/Plugin/jsonapi/FieldEnhancer/Base64Image.php
  docroot/profiles/custom/sul_profile/modules/sul_helper/sul_helper.install
  docroot/profiles/custom/sul_profile/modules/sul_helper/sul_helper.module
  docroot/profiles/custom/sul_profile/tests/codeception/acceptance/SubThemeCest.php
Labels: size/s

#60 2.2.0
  CHANGELOG.md
  composer.lock
Labels: minor, size/xs

#61 Devops-XXX - Ddev config update
  .ddev/config.yaml
  .gitignore
  blt/deploy-exclude-additions.txt
  docroot/sites/library/settings/default.local.settings.php
Labels: size/xs

#62 2.2.1
  CHANGELOG.md
  composer.lock
  docroot/profiles/custom/sul_profile/composer.json
  docroot/profiles/custom/sul_profile/config/sync/core.extension.yml
  docroot/profiles/custom/sul_profile/config/sync/ds.settings.yml
  docroot/profiles/custom/sul_profile/config/sync/ds_extras.settings.yml
  docroot/profiles/custom/sul_profile/config/sync/file.settings.yml
Labels: patch, size/s

#57 NoJira: Lando Setup Fixes
  lando/example.lando.yml
  lando/example.local.blt.yml
Labels: size/xs

#63 Enable SUL fields in Graphql
  composer.lock
  docroot/profiles/custom/sul_profile/config/sync/graphql_compose.settings.yml
  docroot/profiles/custom/sul_profile/config/sync/imagemagick.settings.yml
  docroot/profiles/custom/sul_profile/config/sync/views.view.stanford_basic_pages.yml
  docroot/profiles/custom/sul_profile/config/sync/views.view.stanford_events.yml
  docroot/profiles/custom/sul_profile/config/sync/views.view.stanford_news.yml
  docroot/profiles/custom/sul_profile/config/sync/views.view.stanford_person.yml
  docroot/profiles/custom/sul_profile/config/sync/views.view.stanford_shared_tags.yml
  docroot/profiles/custom/sul_profile/config/sync/views.view.sul_study_places.yml
  docroot/profiles/custom/sul_profile/modules/sul_helper/src/Plugin/GraphQLCompose/FieldType/SulLinkItem.php
  docroot/profiles/custom/sul_profile/modules/sul_helper/src/Plugin/GraphQLCompose/SchemaType/LinkAttributesType.php
  docroot/profiles/custom/sul_profile/modules/sul_helper/src/Plugin/GraphQLCompose/SchemaType/SulLinkType.php
  docroot/profiles/custom/sul_profile/modules/sul_helper/sul_helper.module
Labels: size/s

#65 Fix SUL unit tests
  .github/workflows/tests.yml
  blt/blt.yml
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/tests/src/Unit/Plugin/migrate/process/LibCalLookupProcessTest.php
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/tests/src/Unit/Plugin/migrate/process/LibGuideLookupProcessTest.php
  docroot/profiles/lagunita/sul_profile/tests/src/Unit/EventSubscriber/EventSubscriberTest.php
  docroot/profiles/lagunita/supress/tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  docroot/profiles/lagunita/supress/tests/codeception/acceptance/SubThemeCest.php
  tests/phpunit/example.phpunit.xml
Labels: size/s
