Repository SU-SWS/ace-stanfordlagunita, pull requests merged in 2024-03, with the labels that each got.

#67 Lando update
  .gitignore
  composer.json
  docs/lando.md
  lando/codeception.yml
  lando/example.lando.yml
  lando/example.local.blt.yml
  lando/example.local.sites.php
  lando/example.php.ini
  lando/setup_lando.sh
Labels: size/s

#72 SUL23-417 - Place of Study cards (room number, name, and image)
  docroot/profiles/lagunita/sul_profile/config/sync/core.entity_form_display.node.sul_study_place.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/core.entity_view_display.node.sul_study_place.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/core.entity_view_display.node.sul_study_place.teaser.yml
  docroot/profiles/lagunita/sul_profile/config/sync/field.field.node.sul_study_place.sul_study__image.yml
  docroot/profiles/lagunita/sul_profile/config/sync/field.field.node.sul_study_place.sul_study__room_donor_name.yml
  docroot/profiles/lagunita/sul_profile/config/sync/field.field.node.sul_study_place.sul_study__room_number.yml
  docroot/profiles/lagunita/sul_profile/config/sync/field.storage.node.sul_study__image.yml
  docroot/profiles/lagunita/sul_profile/config/sync/field.storage.node.sul_study__room_donor_name.yml
  docroot/profiles/lagunita/sul_profile/config/sync/field.storage.node.sul_study__room_number.yml
  docroot/profiles/lagunita/sul_profile/config/sync/graphql_compose.settings.yml
  docroot/profiles/lagunita/sul_profile/config/sync/paragraphs.paragraphs_type.stanford_lists.yml
  docroot/profiles/lagunita/sul_profile/config/sync/user.role.layout_builder_user.yml
Labels: size/s

#74 Fix Library video test
  .github/workflows/tests.yml
  docroot/profiles/lagunita/sul_profile/tests/codeception/functional/Paragraphs/WYSIWYGCest.php
Labels: size/xs

#75 Disable subtheme test for summer profile
  docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/SubThemeCest.php
Labels: size/xs

#76 2.4.0
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: minor, size/s

#78 2.4.1
  composer.json
  composer.lock
  patches/contrib/graphql-logging.patch
Labels: size/s

#79 DEVOPS -- Moving to local config.
  .ddev/config.yaml
Labels: size/xs

#77 Added Migration authentication for filemaker api for Press
  composer.json
  composer.lock
  docroot/profiles/lagunita/supress/config/sync/core.extension.yml
  docroot/profiles/lagunita/supress/modules/supress_helper/src/Plugin/migrate_plus/authentication/FileMakerAuth.php
  docroot/profiles/lagunita/supress/modules/supress_helper/supress_helper.info.yml
  docroot/profiles/lagunita/supress/modules/supress_helper/tests/src/Unit/Plugin/migrate_plus/authentication/FileMakerAuthTest.php
Labels: patch, size/s
