Repository SU-SWS/ace-stanfordlagunita, pull requests merged in 2025-09, with the labels that each got.

#207 SUL23-835 | adjust events view and add sul button background variant
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/views.view.sul_events.yml
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/src/Plugin/paragraphs/Behavior/SimpleButtonBehaviors.php
Labels: size/l, size/xs

#211 3.0.0
  CHANGELOG.md
  composer.lock
Labels: major, size/xs

#212 3.0.0
  .github/workflows/release.yml
Labels: major

#213 SUP: Add permission to run importer from the UI
  composer.lock
  docroot/profiles/lagunita/supress/config/sync/split/supress/config_split.patch.user.role.site_manager.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_awards.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_book_prices.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_book_toc.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_import_books.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_social_links.yml
Labels: size/xs

#216 SUM-335: Adjust algolia indexing to include links
  composer.lock
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.search_api.index.algolia_search.yml
Labels: size/s

#217 3.0.1
  CHANGELOG.md
Labels: patch, size/xs
