Repository SU-SWS/ace-stanfordlagunita, pull requests merged in 2025-02, with the labels that each got.

#162 2.7.1
  CHANGELOG.md
  composer.lock
Labels: patch

#163 SUL23-723: added Additional Info field to places to study
  docroot/profiles/lagunita/sul_profile/config/sync/graphql_compose.settings.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/core.entity_form_display.node.sul_study_place.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/core.entity_view_display.node.sul_study_place.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/core.entity_view_display.node.sul_study_place.teaser.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/field.field.node.sul_study_place.sul_study__additional_info.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/field.storage.node.sul_study__additional_info.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/views.view.sul_study_places.yml
Labels: size/s

#164 SUL23-721: Added sticky at the top of lists option to places to study
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/core.entity_form_display.node.sul_study_place.default.yml
Labels: size/xs
