Repository SU-SWS/ace-stanfordlagunita, pull requests merged in 2025-05, with the labels that each got.

#173 SUM-316 Add learner type taxonomy and list display
  composer.lock
  docroot/profiles/lagunita/summer_profile/config/sync/graphql_compose.settings.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.field.field.paragraph.stanford_lists.su_list_view.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_form_display.node.sum_summer_courses.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_form_display.taxonomy_term.sum_course_learner.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.node.sum_summer_courses.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.node.sum_summer_courses.search_indexing.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.node.sum_summer_courses.stanford_card.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.node.sum_summer_courses.stanford_h3_card.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.node.sum_summer_courses.teaser.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/field.field.node.sum_summer_courses.sum_course_learner.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/field.storage.node.sum_course_learner.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/migrate_plus.migration.sum_csv_summer_courses.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/rabbit_hole.behavior_settings.taxonomy_vocabulary_sum_course_learner.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/splide.optionset.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/taxonomy.vocabulary.sum_course_learner.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/views.view.sum_courses.yml
Labels: size/m

#179 Release 2.8.2
  CHANGELOG.md
  composer.json
  composer.lock
Labels: size/s

#180 back to dev
  composer.json
  composer.lock
Labels: size/xs

#183 SUL23-789 | add boolean for rosette in horizontal card behaviors
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/src/Plugin/paragraphs/Behavior/CardBehaviors.php
Labels: size/xs

#182 SUL23-769 | update SUL ckeditor html styles and add location link style
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.editor.editor.stanford_html.yml
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/css/sul_helper.node_form.css
Labels: size/s

#184 SUM-328: Add grading taxonomy and field to summer courses
  docroot/profiles/lagunita/summer_profile/config/sync/graphql_compose.settings.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.search_api.index.algolia_search.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.user.role.site_editor.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.user.role.site_manager.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_form_display.node.sum_summer_courses.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_form_display.taxonomy_term.sum_course_grading.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.node.sum_summer_courses.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.node.sum_summer_courses.search_indexing.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.node.sum_summer_courses.stanford_card.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.node.sum_summer_courses.stanford_h3_card.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.node.sum_summer_courses.teaser.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/field.field.node.sum_summer_courses.sum_course_grading.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/field.storage.node.sum_course_grading.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/migrate_plus.migration.sum_csv_summer_courses.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/rabbit_hole.behavior_settings.taxonomy_vocabulary_sum_course_grading.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/taxonomy.vocabulary.sum_course_availability.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/taxonomy.vocabulary.sum_course_grading.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/taxonomy.vocabulary.sum_course_interest_area.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/taxonomy.vocabulary.sum_course_population.yml
  docroot/profiles/lagunita/supress/supress.profile
Labels: size/s

#185 SUL23-792 | update ckeditor configs
  docroot/profiles/lagunita/sul_profile/config/sync/editor.editor.stanford_html.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.editor.editor.stanford_html.yml
Labels: size/xs
