Repository SU-SWS/ace-stanfordlagunita, pull requests merged in 2025-03, with the labels that each got.

#166 SUL23-722: Allow selection of location hour on study place content
  blt/src/Blt/Plugin/Commands/LagunitaHooksCommands.php
  docroot/profiles/lagunita/sul_profile/config/sync/graphql_compose.settings.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/core.entity_form_display.node.sul_library.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/core.entity_form_display.node.sul_study_place.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/core.entity_view_display.node.sul_study_place.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/core.entity_view_display.node.sul_study_place.teaser.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/field.field.node.sul_study_place.sul_study__hours.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/field.storage.node.sul_study__hours.yml
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/config/schema/sul_helper.schema.yml
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/src/Plugin/Field/FieldWidget/SulBranchSelectorWidget.php
Labels: size/s

#167 SUM: Add classes to paragraph types to support authoring styles
  .github/workflows/tests.yml
  composer.json
  composer.lock
  docroot/profiles/lagunita/summer_profile/composer.json
  docroot/profiles/lagunita/summer_profile/config/sync/config_split.config_split.summer.yml
  docroot/profiles/lagunita/summer_profile/config/sync/core.extension.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/blazy.settings.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.paragraph.sum_at_a_glance.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.paragraph.sum_carousel.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.paragraph.sum_pill_banner.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.paragraph.sum_testimonial.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_mode.media.splide.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/image.style.splide_media.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/migrate_plus.migration.sum_csv_summer_courses.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/splide.optionset.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/splide.optionset.sum_carousel.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/splide.settings.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/views.view.sum_media.yml
  docroot/profiles/lagunita/summer_profile/config/sync/stage_file_proxy.settings.yml
  docroot/profiles/lagunita/summer_profile/config/sync/views.view.content.yml
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerAtAGlanceBehaviors.php
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerBannerBehaviors.php
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCarouselBehaviors.php
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerPillBannerBehaviors.php
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerTestimonialBannerBehaviors.php
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerTopBannerBehaviors.php
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/summer_helper.module
Labels: size/l

#169 Release 2.8.0
  CHANGELOG.md
  composer.json
  composer.lock
Labels: minor, size/xs

#170 back to dev
  composer.json
  composer.lock
Labels: size/xs

#171 SUP: Import epub and pdf data for ebooks
  composer.lock
  docroot/profiles/lagunita/supress/config/sync/core.extension.yml
  docroot/profiles/lagunita/supress/config/sync/graphql_compose.settings.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/config_split.patch.user.role.site_manager.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_form_display.node.sup_book.default.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_form_display.press.prices.default.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.node.sup_book.default.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.node.sup_book.search_indexing.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.node.sup_book.stanford_card.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.node.sup_book.stanford_h3_card.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.node.sup_book.teaser.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.press.prices.default.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.press.prices.search_indexing.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.field.node.sup_book.sup_book_epub_format.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.field.node.sup_book.sup_book_pdf_format.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.field.press.prices.sup_digital_price.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.storage.node.sup_book_epub_format.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.storage.node.sup_book_pdf_format.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.storage.press.sup_digital_price.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_book_prices.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_import_books.yml
  docroot/profiles/lagunita/supress/config/sync/stage_file_proxy.settings.yml
  docroot/profiles/lagunita/supress/modules/supress_helper/supress_helper.module
Labels: size/m

#168 SUM: Editing the display of the page's preview.
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.paragraph.sum_arc_banner.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.paragraph.sum_pill_banner.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.paragraph.sum_testimonial.default.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/core.entity_view_display.paragraph.sum_top_banner.default.yml
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/styles/dist/css/admin.css
  docroot/profiles/lagunita/summer_profile/modules/summer_helper/styles/lib/admin/index.scss
Labels: size/m
