Repository SU-SWS/ace-stanfordlagunita, pull requests merged in 2025-08, with the labels that each got.

#197 SUP: Add alternative price data
  composer.lock
  docroot/profiles/lagunita/supress/config/sync/graphql_compose.settings.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_form_display.node.sup_book.default.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_form_display.press.prices.default.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.node.sup_book.default.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.node.sup_book.search_indexing.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.node.sup_book.stanford_card.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.node.sup_book.stanford_h3_card.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.node.sup_book.teaser.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.press.prices.default.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/core.entity_view_display.press.prices.search_indexing.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.field.node.sup_book.sup_book_alt_format.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.field.press.prices.sup_alt_price.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.storage.node.sup_book_alt_format.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.storage.press.sup_alt_price.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_book_prices.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_import_books.yml
Labels: size/m

#198 release 2.8.10
  CHANGELOG.md
  composer.lock
Labels: patch, size/xs, size/m

#172 Replace BLT with SWS Drush commands
  .github/sup-check-pages.sh
  .github/workflows/deploy-main-branches.yml
  .github/workflows/release.yml
  .github/workflows/sup-check-pages.yml
  .github/workflows/tests.yml
  .github/workflows/weekly-cleanup.yml
  blt/.gitignore
  blt/.schema_version
  blt/blt.yml
  blt/ci.blt.yml
  blt/deploy-exclude-additions.txt
  blt/deploy/rsync-exclude.txt
  blt/example.local.blt.yml
  blt/src/Blt/Plugin/Commands/LagunitaAcquiaApiCommands.php
  blt/src/Blt/Plugin/Commands/LagunitaCommands.php
  blt/src/Blt/Plugin/Commands/LagunitaHooksCommands.php
  composer.json
  composer.lock
  docroot/profiles/lagunita/supress/modules/supress_helper/src/Plugin/QueueWorker/BookCoverDownloader.php
  docroot/sites/default/settings.php
  docroot/sites/default/sws.yml
  docroot/sites/library/settings.php
  docroot/sites/library/settings/includes.settings.php
  docroot/sites/library/sws.yml
  docroot/sites/settings/config.settings.php
  docroot/sites/settings/early.settings.php
  docroot/sites/settings/environment_indicator.settings.php
  docroot/sites/settings/fast404.settings.php
  docroot/sites/settings/global.settings.php
  docroot/sites/settings/saml.settings.php
  docroot/sites/settings/xmlsitemap.settings.php
  docroot/sites/summer/settings.php
  docroot/sites/summer/settings/includes.settings.php
  docroot/sites/summer/sws.yml
  docroot/sites/supress/settings.php
  docroot/sites/supress/settings/includes.settings.php
  docroot/sites/supress/sws.yml
  drush/deploy-cleanup.sh
  drush/deploy.gitignore
  drush/drush.yml
  drush/lagunita/src/.gitkeep
  hooks/common/post-code-deploy/post-code-deploy.sh
  hooks/common/post-code-update/post-code-update.sh
  hooks/common/post-db-copy/db-scrub.sh
  hooks/common/post-db-copy/post-db-copy.sh
  hooks/common/post-files-copy/post-files-copy.sh
Labels: size/l

#199 2.9.0
  CHANGELOG.md
  composer.lock
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.core.entity_form_display.node.stanford_event.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.core.entity_form_display.node.stanford_person.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.field.field.node.stanford_person.field_menulink.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.migrate_plus.migration.stanford_course_depts.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.migrate_plus.migration.stanford_courses.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.migrate_plus.migration.stanford_events_importer.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.migrate_plus.migration.stanford_localist_importer.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.migrate_plus.migration.stanford_publications.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.migrate_plus.migration.su_stanford_person.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.user.role.layout_builder_user.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/stage_file_proxy.settings.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.migrate_plus.migration.stanford_course_depts.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.migrate_plus.migration.stanford_courses.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.migrate_plus.migration.stanford_events_importer.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.migrate_plus.migration.stanford_localist_importer.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.migrate_plus.migration.stanford_publications.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/config_split.patch.migrate_plus.migration.su_stanford_person.yml
  docroot/profiles/lagunita/summer_profile/config/sync/split/summer/migrate_plus.migration.sum_csv_summer_courses.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/config_split.patch.field.field.paragraph.stanford_lists.su_list_view.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/config_split.patch.migrate_plus.migration.stanford_course_depts.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/config_split.patch.migrate_plus.migration.stanford_courses.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/config_split.patch.migrate_plus.migration.stanford_events_importer.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/config_split.patch.migrate_plus.migration.stanford_localist_importer.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/config_split.patch.migrate_plus.migration.stanford_publications.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/config_split.patch.migrate_plus.migration.su_stanford_person.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/field.field.node.sup_book.sup_book_authors.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_awards.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_book_toc.yml
  docroot/profiles/lagunita/supress/config/sync/split/supress/migrate_plus.migration.sup_social_links.yml
Labels: minor, size/s

#202 SUL23-815 | enable stat card graphql fragments and add layout options config
  docroot/profiles/lagunita/sul_profile/config/sync/graphql_compose.settings.yml
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/layouts/one_column/one-column.css
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/layouts/one_column/sul-one-column.html.twig
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/layouts/three_column/sul-three-column.html.twig
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/layouts/three_column/three-column.css
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/layouts/two_column/sul-two-column.html.twig
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/layouts/two_column/two-column.css
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/src/Layouts/SulThreeColumn.php
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/src/Layouts/SulTwoColumn.php
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/sul_helper.layouts.yml
  docroot/profiles/lagunita/sul_profile/modules/sul_helper/sul_helper.libraries.yml
  docroot/profiles/lagunita/summer_profile/tests/codeception/functional/Content/PersonCest.php
  docroot/profiles/lagunita/summer_profile/tests/codeception/functional/Content/PublicationCest.php
  docroot/profiles/lagunita/supress/tests/codeception/functional/Content/PersonCest.php
  docroot/profiles/lagunita/supress/tests/codeception/functional/Content/PublicationCest.php
Labels: size/xs, size/s

#204 SUL23-834 | add experience field to sul localist importer
  docroot/profiles/lagunita/sul_profile/config/sync/graphql_compose.settings.yml
  docroot/profiles/lagunita/sul_profile/config/sync/migrate_plus.migration.stanford_localist_importer.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.core.entity_form_display.node.stanford_event.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.core.entity_view_display.node.stanford_event.default.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.core.entity_view_display.node.stanford_event.search_indexing.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.core.entity_view_display.node.stanford_event.stanford_card.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.core.entity_view_display.node.stanford_event.stanford_h3_card.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.core.entity_view_display.node.stanford_event.teaser.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/config_split.patch.field.field.node.stanford_person.field_menulink.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/field.field.node.stanford_event.sul_event_experience.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/field.storage.node.sul_event_experience.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/stage_file_proxy.settings.yml
  docroot/profiles/lagunita/sul_profile/config/sync/split/library/views.view.sul_events.yml
Labels: size/xs, size/s

#206 release 2.9.1
  composer.lock
Labels: patch
